<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://gateway-lon.watsonplatform.net/text-to-speech/api/v1/synthesize');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"text\":\"hello world\"}");
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_USERPWD, 'apikey' . ':' . 'Sct3Rx7QrWsUnfdiiu7X-12oV2mlUw60pAlfmWv1RZau');

$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Accept: audio/mp3';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
echo $result;

curl_close ($ch);
?>